user_email = "#id_email"
user_password = "#id_password"
remember_password = "#label_email_remember"
login_submit = "#login-form-submit"
forgot_your_password = ".t-alignR.ts-s>a"
email_error_div = "#id_email_error"
password_error_div = "#id_password_error"
afater_login_dashboard_div = ".box-row.pa-4.cf"