scratcher_code = "#id_code"
scratcher_inline_error = "#id_code_error"
tooltip_description = "#tooltip-id_code"
# tool_icon = ".icon-tooltip"
tool_icon = ".trigger-tooltip .icon-tooltip"
scratcher_page = ".pt-6.p-rel"
scrtcher_submit = "#scratcher-submit"
scrtcher_form_title = ".h2.has-note.mb-1"
scrtcher_form_desc_text = ".g-b.g-b--1of1.g-b--m--7of9.px-0.m--pl4>p"
scrtcher_fan_iamge = ".pt-6.p-rel .fit[src='/static/web/images/generic-scratchers-fan-%402x.png']"
you_have_claimed_your_scratcher_page = ".scratcher-claim-notify.rb-2.border-am-grey3.mb-5.bg-white.pa-4"
already_redeemed_scratcher_link = "#id_code_error>a[href='/activity/scratcher-claim']"
activity_scratcher_claim_filter = ".grey-pill.active"
whats_next_page = ".bg-white.border-am-grey3.rb-2.pa-3.m--pa5.mb-2"
claim_a_scratcher_nav_button = "#global-nav-claim-scratcher"