signup_form = "#home-signup-form-box"
first_name = "#id_first_name"
email_address = "#id_email"
password = "#id_password"
confirm_password = "#id_confirm_password"
create_account_btn = ".btn-blue.btn-l.mb-1"
first_name_error = "#id_first_name_error"
email_error = "#id_email_error"
password_error = "#id_password_error"
confirm_password_error = "#id_confirm_password_error"
tooltip_icon = ".icon-tooltip"
tooltip_password_div = "#tooltip-id_password .mb-0"
signup_scratcher_form = ".pt-6.p-rel"
terms_url = ".submit-help.ts-s.t-alignL.mb-2>a[href='/legal/terms']"
privacy_url = ".submit-help.ts-s.t-alignL.mb-2>a[href='/legal/privacy']"
legal_text_block = ".submit-help.ts-s.t-alignL.mb-2"
term_of_services_link = ".//*[@id='signup-home']/div[2]/p/a[1]"
privacy_policy_page = ".border-am-grey3.bg-white.rb-2.pa-4"
terms_of_use_page = ".border-am-grey3.bg-white.rb-2.pa-4"


