welcome_div = ".border-am-grey3.rb-2.bg-white.mb-4"
welcome_pete = ".fit[src='/static/web/images/pete/pete-bigarms.png']"
h2_welcome_to_payperks = ".h2.mb-0.pt-2"
welcome_description = ".mt-1"
signup_now = ".button.btn-blue.btn-l[href='/?utm_source=what-we-do&utm_medium=SignUpButton&utm_campaign=AboutUs']"
signup_form_after_btn_click = "#home-signup-form-box"
section_nav_block = ".section-nav-block.g-b.g-b--1of1.g-b--m--3of12.m--pt2.m--pb2.m--pl0.m--pr3"
what_we_do_1st_list_item = ".section-nav-link.db.px-3.about-us.active[href='/about/what-we-do']"
how_it_work_2nd_list_item = ".section-nav-link.db.px-3.how-it-works[href='/about/how-it-works']"
in_the_new_3rd_list_item = ".section-nav-link.db.px-3.what-people-think[href='/about/what-people-think']"
saftey_security_4th_list_item =".section-nav-link.db.px-3.why-safetys-first[href='/about/why-safetys-first']"
our_psrtner_5th_list_item = ".section-nav-link.db.px-3.our-partners[href='/about/our-partners']"
our_team_6th_list_item = ".section-nav-link.db.px-3.our-team[href='/about/our-team']"
contact_us_7th_list_item = ".section-nav-link.db.px-3.where-to-connect[href='/about/where-to-connect']"
what_we_do_section = "#who-we-are"
learn_cap_iamge = ".fit[src=' /static/web/images/about-learncap.png']"
prize_monthly_image = ".fit-h[src=' /static/web/images/about-prizesmonthly.png']"
icone_lock_image = ".fit[src='/static/web/images/icons/ico-lock.png']"
point1_perks_for_earning = ".mb-4 li:nth-child(1)"
point2_prizes_each_month = ".mb-4 li:nth-child(2)"
point3_your_security_comes_first = ".mb-4 li:nth-child(3)"
h3_what_we_do ="#who-we-are .h3"
point1_text_h3 = ".//*[@id='who-we-are']/div/ol/li[1]/div[2]/h3"
point2_text_h3 = ".//*[@id='who-we-are']/div/ol/li[2]/div[2]/h3"
point3_text_h3 = ".//*[@id='who-we-are']/div/ol/li[3]/div[2]/h3"
point1_description =".//*[@id='who-we-are']/div/ol/li[1]/div[2]/p"
point2_description = ".//*[@id='who-we-are']/div/ol/li[2]/div[2]/p"
point3_description = ".//*[@id='who-we-are']/div/ol/li[3]/div[2]/p"
what_we_do_bottom_signup = ".pa-4.mb-0.t-alignC"
bottom_signp_button = ".pa-4.mb-0.t-alignC>a[href='/']"